---
- name: Creating a user
  hosts:  server
  become: true
  become_user:  root
  vars_files:
    - vars_file.yaml

  tasks:
    - name: Creating a user 
      user:
        name: "{{user_name}}"
        group: admin
        comment: user for executing the node app 
      

- name: Install Node and npm
  hosts: server
  # remote_user: root
  become: true
  become_user:  root

  tasks:
    - name: update apt repo and cache
      apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Instll Node and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Deploy node app
  hosts: server
  become: true
  become_user: root
  # remote_user: nilesh
  vars:
    - source_of_nodeApp_on_local: /home/nodejs-app-1.0.0.tgz # method 1 for defining variable
                                                            # method 2 is pass variable during runtime
  vars_files:
    - vars_file.yaml

  tasks:
    - name: Copy local to remote server
      copy:
        src: "{{source_of_nodeApp_on_local}}"
        dest: /home/{{user_name}}/nodejs-app-{{version}}.tgz  # Method 3 is use it in external variable file and load file in every play where variable is used

    - name: Unpack the node app
      unarchive:
        src: /home/{{user_name}}/nodejs-app-1.0.0.tgz
        dest: /home/{{user_name}}/
        remote_src: yes

    - name: Install dependency from package json
      npm:
        path: /home/{{user_name}}/package
      register: package_json_status
    - debug: msg={{package_json_status}}

    - name: start application
      command:
        chdir: /home/{{user_name}}/package/app
        cmd: node server
      async: 1000
      poll: 0

    - name: Ensure App is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status}}

        
    



